apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose --provider openshift --file docker-compose.yml
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    io.kompose.service: nginx
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: ' '
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /home/invenio/.virtualenvs/invenio/var/instance/static
          name: static-claim0
      restartPolicy: Always
      volumes:
      - name: static-claim0
        persistentVolumeClaim:
          claimName: static-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nginx
      from:
        kind: ImageStreamTag
        name: nginx:latest
    type: ImageChange
status: {}
