apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: postgres
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
