apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: rabbitmq
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
