apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose --provider openshift --file docker-compose.yml
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: "24369"
    port: 24369
    targetPort: 4369
  - name: "45672"
    port: 45672
    targetPort: 25672
  selector:
    io.kompose.service: rabbitmq
status:
  loadBalancer: {}
